fix: test suite

diff --git a/JenkinsWorkflows/Jenkinsfile-google b/JenkinsWorkflows/Jenkinsfile-google
--- a/JenkinsWorkflows/Jenkinsfile-google
+++ b/JenkinsWorkflows/Jenkinsfile-google
@@ -105,7 +105,20 @@ pipeline {
 					"Kubesec Scan": {
 						dir("infra") {
 							dir("k8s-dev") {
-								sh "bash google-kubesec-scan.sh"
+								sh '''
+									scan_result=$(docker run -i kubesec/kubesec:512c5e0 scan /dev/stdin < google-depl-dev.yaml)
+									scan_message=$(docker run -i kubesec/kubesec:512c5e0 scan /dev/stdin < google-depl-dev.yaml | jq .[].message -r)
+									scan_score=$(docker run -i kubesec/kubesec:512c5e0 scan /dev/stdin < google-depl-dev.yaml | jq .[].score)
+
+									if [[ "${scan_score}" -ge 4 ]]; then
+										echo "Score is $scan_score"
+										echo "Kubesec Scan $scan_message"
+									else
+										echo "Score is $scan_score, which is less than or equal to 5."
+										echo "Scanning Kubernetes Resource has Failed"
+										exit 1;
+									fi;
+								'''
 							}
 						}
 					},
