fix pipeline syntax

diff --git a/JenkinsWorkflows/Jenkinsfile-google b/JenkinsWorkflows/Jenkinsfile-google
--- a/JenkinsWorkflows/Jenkinsfile-google
+++ b/JenkinsWorkflows/Jenkinsfile-google
@@ -143,20 +143,19 @@ pipeline {
 						dir("infra/k8s-dev") {
 							script {
 								withKubeConfig([credentialsId: 'kubeconfig']) {
-									sleep(60)
-							
-									// Check the rollout status of the deployment
-									def rolloutStatus = sh(script: "kubectl -n dev rollout status deploy ${deploymentName} --timeout 10s", returnStatus: true).toString().trim()
-									
-									// If rollout status indicates failure, undo the deployment
-									if (rolloutStatus != 0) {
-										echo "Deployment ${deploymentName} Rollout has Failed"
-										sh "kubectl -n dev rollout undo deploy ${deploymentName}"
-										error "Deployment rollback triggered due to rollout failure"
-									} else {
-										echo "Deployment ${deploymentName} Rollout is Success"
-									}
+								sh '''
+									#!/bin/bash
+									sleep 60s
 
+									if [[ $(./kubectl -n dev rollout status deploy ${deploymentName} --timeout 5s) != *"successfully rolled out"* ]]; 
+									then     
+										echo "Deployment ${deploymentName} Rollout has Failed"
+										kubectl -n dev rollout undo deploy ${deploymentName}
+										exit 1;
+									else
+										echo "Deployment ${deploymentName} Rollout is Success"
+									fi
+								''' 
 								}
 							}
 						}
